#Tomcat配置
server:
  port: 8081
  servlet:
    context-path: /a
#系统配置
system:
  config:
    name: Smart.Develop 系统

spring:
  application:
    name: DubboCustomer

#版本
version: 1.0.0

#AES加密Key
aeskey: 123456

#静态文件后缀
webStaticFile: .css,.js,.png,.jpg,.gif,.jpeg,.bmp,.ico,.swf,.psd,.htc,.htm,.html,.crx,.xpi,.exe,.ipa,.apk